server:
  port: 8081

#spring:
#  datasource:
#   url: jdbc:mysql://localhost:3306/dbspotify?createDatabaseIfNotExist=true
#    username: root
#    password:
#    driverClassName: com.mysql.cj.jdbc.Driver
#  application:
#    name: spotify-clone

#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



info:
  application:
    name: spotify-clone
    version: '@project.version@'

application:
  security:
    jwt:
      secret-key: 59d407208c0bfb4fc52780506cdecd71cbde23b4dd622bc80d84b66e9efc4dd2